import { StyleSheet } from "react-native";

const BRAND = "#0D3B66";
const BORDER = "#E5E7EB";
const MUTED = "#F3F4F6";

export const trackScreenStyles = StyleSheet.create({
  screen: { 
    flex: 1, 
    padding: 16, 
    paddingTop: 32,
    alignItems: "center",
    maxWidth: 800,
    alignSelf: "center",
    width: "100%",
  },
  title: { fontSize: 20, fontWeight: "700" },
  map: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#cbd5e1",
    borderRadius: 10,
    backgroundColor: MUTED,
  },

  // Interactive Map Styles
  mapContainer: {
    alignSelf: "center",
    width: "90%",
    maxWidth: 600,
    height: 300,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    backgroundColor: MUTED,
    borderWidth: 2,
    borderColor: BORDER,
    position: "relative",
  },
  mapBackground: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F0FDF4",
    position: "relative",
  },
  gridOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.2,
    backgroundColor: "transparent",
  },

  // Buildings
  building1: {
    position: "absolute",
    top: "10%",
    left: "10%",
    width: "15%",
    height: "15%",
    backgroundColor: "#9CA3AF",
    borderRadius: 4,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
    zIndex: 2,
  },
  building2: {
    position: "absolute",
    top: "75%",
    left: "75%",
    width: "20%",
    height: "12%",
    backgroundColor: "#6B7280",
    borderRadius: 4,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
    zIndex: 2,
  },
  building3: {
    position: "absolute",
    top: "15%",
    right: "15%",
    width: "18%",
    height: "20%",
    backgroundColor: "#4B5563",
    borderRadius: 4,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
    zIndex: 2,
  },

  // Markers
  userMarker: {
    position: "absolute",
    left: "45%",
    top: "60%",
    zIndex: 10,
  },
  proMarker: {
    position: "absolute",
    zIndex: 10,
  },
  markerDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  userDot: {
    backgroundColor: "#1E40AF",
  },
  proDot: {
    backgroundColor: "#F59E0B",
  },
  tooltip: {
    position: "absolute",
    bottom: "100%",
    left: "50%",
    marginBottom: 12,
    backgroundColor: "rgba(0,0,0,0.9)",
    color: "#fff",
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    transform: [{ translateX: -50 }],
  },

  // Info Panel
  infoPanel: {
    position: "absolute",
    top: 20,
    left: 20,
    right: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    fontSize: 16,
    zIndex: 15,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  infoLabel: {
    color: "#6B7280",
    fontWeight: "500",
  },
  infoValue: {
    fontWeight: "700",
    color: "#111827",
  },

  // Map Controls
  mapControls: {
    position: "absolute",
    bottom: 20,
    right: 20,
    flexDirection: "column",
    gap: 8,
    zIndex: 15,
  },
  mapButton: {
    width: 44,
    height: 44,
    backgroundColor: "#fff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  mapButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#374151",
  },

  // Status Container
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
    borderWidth: 2,
  },
  statusDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginRight: 12,
  },
  statusText: {
    fontSize: 18,
    fontWeight: "600",
  },

  // Button Container
  buttonContainer: {
    flexDirection: "row",
    gap: 16,
  },
  button: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  primaryButton: {
    backgroundColor: "#2563EB",
    borderColor: "#2563EB",
    shadowColor: "#2563EB",
    shadowOpacity: 0.25,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  secondaryButton: {
    backgroundColor: "#F3F4F6",
    borderColor: BORDER,
  },
  secondaryButtonText: {
    color: "#374151",
    fontWeight: "600",
    fontSize: 16,
  },

  // overlay
  veil: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.35)" },
  centerWrap: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", padding: 16 },
  sheet: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    alignItems: "center",
  },

  // photo
  photoWrap: {
    width: 84,
    height: 84,
    borderRadius: 42,
    overflow: "hidden",
    borderWidth: 3,
    borderColor: BRAND,
    marginBottom: 8,
  },
  photo: { width: "100%", height: "100%", resizeMode: "cover" },

  proName: { fontSize: 18, fontWeight: "800", color: "#111827", marginTop: 4 },
  proSub: { color: "#374151", marginTop: 2 },
  row: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", justifyContent: "center" },
  badge: {
    backgroundColor: MUTED,
    borderColor: BORDER,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginHorizontal: 4,
    color: "#111827",
  },
  sep: { color: "#9CA3AF", marginHorizontal: 2 },
  btn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    marginHorizontal: 6,
    minWidth: 140,
    alignItems: "center",
  },
  btnPrimary: { backgroundColor: BRAND, borderColor: BRAND },
  btnPrimaryText: { color: "#fff", fontWeight: "700" },
  btnGhost: { backgroundColor: "#fff" },
  btnGhostText: { color: "#111827", fontWeight: "700" },
});

export { BRAND, BORDER, MUTED };
