# Generated by Django 5.0.2 on 2025-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=50, unique=True)),
                ('provider_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('handyman', 'Handyman'), ('mechanic', 'Mechanic'), ('locksmith', 'Locksmith'), ('carpenter', 'Carpenter')], max_length=50)),
                ('eta', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='provider_photos/')),
            ],
            options={
                'ordering': ['-rating', 'provider_name'],
            },
        ),
    ]
