# Generated by Django 5.0.2 on 2025-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='job_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('handyman', 'Handyman')], max_length=50),
        ),
    ]
