# Generated by Django 5.0.2 on 2025-08-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='job_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('handyman', 'Handyman'), ('mechanic', 'Mechanic'), ('locksmith', 'Locksmith'), ('carpenter', 'Carpenter')], max_length=50),
        ),
    ]
