# Generated by Django 5.0.2 on 2025-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
