# Generated by Django 5.0.2 on 2025-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('premium', 'Premium')], default='individual', max_length=20)),
                ('location', models.CharField(choices=[('new_york', 'New York'), ('los_angeles', 'Los Angeles'), ('chicago', 'Chicago'), ('houston', 'Houston'), ('phoenix', 'Phoenix'), ('philadelphia', 'Philadelphia'), ('san_antonio', 'San Antonio'), ('san_diego', 'San Diego'), ('dallas', 'Dallas'), ('san_jose', 'San Jose')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
